version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - PORT=3000
    volumes:
      - ./data:/app/data
      - ./backend/savings.db:/app/backend/savings.db
    restart: unless-stopped
    networks:
      - savings-net

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
    depends_on:
      - webapp
    restart: unless-stopped
    networks:
      - savings-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webapp
    restart: unless-stopped
    networks:
      - savings-net

networks:
  savings-net:
    driver: bridge