services:
  - type: web
    name: savings-tracker-webapp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false

  - type: worker
    name: savings-tracker-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false